name: Build Executable

on:
  workflow_dispatch:

jobs:
  build_UI:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-local.txt --target .
          pip install cx_Freeze

      - name: Build the executable with setupUI.py
        run: |
          python setup.py build

      - name: Zip the GUI executable
        run: |
          powershell Compress-Archive -Path build\exe.win-amd64-3.12\* -DestinationPath PhotoPolarAlign.zip

      - name: Upload zipped GUI executable
        uses: actions/upload-artifact@v4
        with:
          name: PhotoPolarAlign
          path: PhotoPolarAlign.zip
